### PR TITLE
upgpkg: brave 1.48.171-1

### PR DESCRIPTION
**Pull request by caesarw**
### Changelog
* Update `brave` version to 1.48.171
* Update `chromium` version to 110.0.5481.177
* Update `SRCINFO`
* Remove unnecessary patches

Sorry for taking so long for this update. I had some initial building issues and took some time debugging. Turned out that my test build server had insufficient memory (8 GB RAM w/o swap), and eventually solved by enabling `swapfile`.
For [the discussion of distro-shipped Brave](https://community.brave.com/t/does-brave-allow-the-distribution-of-self-compiled-or-distro-compiled-binaries/), there has been some updates. The Brave team would like to establish a variant called _Bravium_ which works similarly as _Chromium_.

### CODE REVIEW

**Comment by alerque** [comment]
This patch is reflected in the AUR now and the built package is in my user repository for those that can't be bothered to build it (and who could blame them!), but I'm having the usual trouble with this particular tree working around `aurpublish` tripping up on an `git subtree` bug, so this PR won't be marked as merged here until I get a chance to re-clone the sources on the machine I use with my modified `git` client on — and I can't reach it today. I just didn't want you to think that was still hanging!

**Comment by caesarw** [comment]
@alerque did the build work on your side? Just asking because I did not see the latest build in your repo.

**Comment by alerque** [comment]
Yes, and I published it ... I thought. I'll double check, perhaps the package database didn't get rebuilt after I uploaded. I was having GPG agent problems that day...

**Comment by alerque** [comment]
Try now! Something did get jammed up...

**Pull request closed without merging**
