### PR TITLE
use sip version 4

### PR DESCRIPTION
**Pull request by srtlg**
fixes the problem you describe
builds with extra-x86_64-build

### CODE REVIEW

**Comment by alerque** [comment]
Hmm. This was actually one of the first things I tried. This exact combination is in my git stash of failed experiments. If you say it works I'll give it another spin and try to figure out if there was something else wrong with my setup.

Thanks for the contribution.

**Comment by alerque** [comment]
Oh I see the difference. This is still compiling the previous release. I was trying to compile the latest release tag. This may be worth posting as an interim so that the old version keeps compiling as well, but it doesn't get us up to date with the latest release.

**Comment by alerque** [comment]
Merging this because it's worth fixing the build issue on the previous version until we figure out the next release, but this doesn't actually solve the issue I posted about in the AUR comments.

**Comment by srtlg** [comment]
I will look into the next release until Friday.  
@alerque Out of curiosity: How did you push the commit of a directory (alerque/aur/python-poppler-qt5) to AUR (python-poppler-qt5)?

**Comment by alerque** [comment]
@srtlg You can push just just directory of a repository to a remote that matches the history of just that directory using `git subtree push`. You can use the `git subtree` tooling directly of course for any repository, but for the use case of AUR I am using `aurpublish` which wraps up the subtree setup including automatically adding the right AUR remote addresses to each package directory in a convenient CLI.

After merging your PR here, all I had to do was `git pull` in my local clone and then `aurpublish python-poppler-qt5` to push the relevant subtree.

**Pull request merged**
