### PR TITLE
Fix build: gittyup

### PR DESCRIPTION
**Pull request by FabioLolix**
Hello,

* switched to git checkout since tarballs don't have git submodules
* switch from org.freedesktop.secrets to libgnome-keyring and libsecret, gittyup explicity depends on 'gnome-keyring-1'
* git source renamed to gittyup, same as in gittyup-git pkgbuild
* package() copied from gittyup-git, it's not your style but works

```
-- Found PkgConfig: /usr/sbin/pkg-config (found version "1.8.0") 
-- Checking for module 'libssh2'
--   Found libssh2, version 1.10.0
CMake Error at dep/libssh2/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /home/fabio/Dev/Github-forks/aur/gittyup/src/Gittyup-gittyup_v1.0.0/dep/libssh2/libssh2

  does not contain a CMakeLists.txt file.


CMake Error at dep/libgit2/CMakeLists.txt:25 (add_subdirectory):
  The source directory

    /home/fabio/Dev/Github-forks/aur/gittyup/src/Gittyup-gittyup_v1.0.0/dep/libgit2/libgit2

  does not contain a CMakeLists.txt file.


CMake Error at dep/libgit2/CMakeLists.txt:26 (target_include_directories):
  Cannot specify include directories for target "git2" which is not built by
  this project.


-- Checking for module 'libcmark'
--   Found libcmark, version 0.30.2
```

```
-- Checking for module 'libcmark'
--   Found libcmark, version 0.30.2
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.20.4
-- Checking for module 'gnome-keyring-1'
--   Package 'gnome-keyring-1', required by 'virtual:world', not found
```

### CODE REVIEW

**Comment by alerque** [comment]
Sorry I'm a bit late seeing this PR. I had been traveling for 7 weeks and was actually home, but am still digging out from the backlog.

I've been watching upstream notifications and it looks like most of the git modules are being ripped out in favor of finding system dependencies via pkg-config. This seems like a good thing to be, but also seems to obsolete many of these changes.

Any feedback? Where the next release is going to land will probably set the tone for how we should package this.

**Comment by FabioLolix** [comment]
> I've been watching upstream notifications and it looks like most of the git modules are being ripped out in favor of finding system dependencies via pkg-config. This seems like a good thing to be, but also seems to obsolete many of these changes.

There have not been significant changes so far, on git master hunspell can be configured out, a new module have been added, for the other modules is the same (libgit2, git and libssh2 are still mandatory)

**Comment by alerque** [comment]
Thanks for the feedback.

I took a stab based on your work at syncing the submodules with Arch's package versions at least so that it is really fair to delete the `*.so` files and use system ones. I tried a couple ways and actually didn't get it to work yet. I'm having trouble with cloning the libgit2 repo though. Can I ask why you used a fork instead of the original? The fork you have doesn't have tags for the version matching Arch Linux's libgit2 package right now (1.4.3).

Note the style changes are because I'm tracking this for inclusion in [community] as soon as we can get reliable stable builds going. If you want to sync to that for ease of diffing great, otherwise they will just be different.

**Comment by FabioLolix** [comment]
> so that it is really fair to delete the *.so files and use system ones. I tried a couple ways and actually didn't get it to work yet.

I've copied that from the githahead pkgbuild and always worked for me

> Can I ask why you used a fork instead of the original?

I use what is in the [.gitmodules](https://github.com/Murmele/Gittyup/blob/master/.gitmodules)
***
Btw, if detected lua is used

` -- Found Lua: /usr/lib/liblua5.4.so;/usr/lib/libm.so (found version "5.4.4") `


` gittyup E: Dependency lua detected and not included (libraries ['usr/lib/liblua.so.5.4'] needed in files ['usr/lib/gittyup/indexer'])`

**Comment by alerque** [comment]
Thanks again for the start on this. Now that it's working I think I'm going to squash/merge as a starting point to get the package to people, but I consider the result I came up with **hideous**. A lot of the blame is on the upstream for vendoring everything wrong and not making it easy to dynamically link anything and also for depending on specific versions and even FORKS of common projects.

Eventually I would move this to [community] if the build can be sanitized to remove all or most of the vendoring and dynamically link the respective system dependencies (git, libgit2, cmark, hunspell, openssl, libssh, etc.). Some of the hacking commits earlier in this PR might be useful in that effort, or maybe not. Either way any contributions either upstream or to this packaging to sanitize it would be very welcome.

**Pull request merged**
