### PR TITLE
upgpkg: pagure 5.10.0-0.1

### PR DESCRIPTION
**Pull request by Conan-Kudo**
upstream release

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@alerque This was the most I was comfortable with changing, and I might have still gotten it wrong. 😅

**Review by alerque — APPROVED** [review]
Thanks for the contribution, this looks good to me! Thanks for renaming the config file name.

**Comment by Conan-Kudo** [comment]
@alerque You may want to review the changes that occurred in the Fedora, openSUSE, and Mageia packages and further enhance as needed.

**Comment by alerque** [comment]
@Conan-Kudo Thanks, I'm sure that would be a good idea but I haven't had time to do more than tinker with this. So far I'm not using it in production, only some local tests. I'm happy to accept help from anybody who is up to speed with what's happening upstream and/or using this in a greater capacity!

**Pull request merged**
