### PR TITLE
Moonray 1.4.0.0

### PR DESCRIPTION
**Pull request by adro79**
Hi! Just updated the PKGBUILD to the lastest Moonray version, also I got able to compile with GCC and TBB.

### CODE REVIEW

**Comment by alerque** [comment]
One of the patches doesn't verify. Did you forget to commit the changes to a patch but commit the new checksum?

**Comment by adro79** [comment]
Yeah I forgot to update the sums sorry, should be okay now

**Comment by alerque** [comment]
I think something is still wrong. You just updated 3 checksums, but only 1 was failing for me before. Now the other two are. I suspect you might have missed committing changes to some of the patches, but I can't prove it. In any case the patches as in the repo now do not apply cleanly so I can't even start a test build.

**Comment by adro79** [comment]
Should be okay now, didn't test it enough.

**Comment by alerque** [comment]
```
CMake Error at moonray/hydra/hdMoonray/CMakeLists.txt:42 (find_package):
  By not providing "Findpxr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pxr", but
  CMake did not find one.

  Could not find a package configuration file provided by "pxr" with any of
  the following names:

    pxrConfig.cmake
    pxr-config.cmake

  Add the installation prefix of "pxr" to CMAKE_PREFIX_PATH or set "pxr_DIR"
  to a directory containing one of the above files.  If "pxr" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

What package is supposed to be supplying pxr stuff?

**Comment by adro79** [comment]
It's weird that **usd** wasn't at the dependency list, I hope you can build it now.

**Comment by alerque** [comment]
```
-- Found CUDAToolkit: /opt/cuda/targets/x86_64-linux/include (found version "12.3.103")
-- Found OptiX: /opt/optix/include
-- The ISPC compiler identification is unknown
CMake Error at moonray/moonray/CMakeLists.txt:7 (project):
  No CMAKE_ISPC_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ISPC" or the CMake cache entry CMAKE_ISPC_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
```

**Comment by alerque** [comment]
We had `usd` and some other things we just hit again before as `makedepends`. You dropped them at some point, and now they are coming back in `dependes`. I'm not too worried about it at this stage while we try to get something that actually builds, but it would be nice to actually keep things that are only build-time dependencies separate.

I get a little farther now, but now hit this:

```
-- Looking for TBB components tbb; (tbbmalloc;tbbmalloc_proxy;tbbbind;tbbpreview)
-- Found existing TBB component targets: tbb;tbbmalloc;tbbmalloc_proxy
-- Found TBB version 2021.11 at /usr
-- Found Boost: /lib/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0") found components: system python date_time chrono
-- Found Boost: /lib/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0") found components: regex
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Could NOT find Mkl (missing: Mkl_INCLUDE_DIR)
-- Found OpenColorIO: /lib/cmake/OpenColorIO/OpenColorIOConfig.cmake (found version "2.3.1")
-- Configuring done (8.3s)
CMake Error in moonray/moonray_gui/cmd/moonray_gui/CMakeLists.txt:
  Target "application" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "Random123_INCLUDE_DIR-NOTFOUND/.."


CMake Error in moonray/hydra/hdMoonray/src/CMakeLists.txt:
  Target "rendering_rndr" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "Random123_INCLUDE_DIR-NOTFOUND/.."


CMake Error in moonray/moonray/lib/application/CMakeLists.txt:
  Target "rendering_rndr" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "Random123_INCLUDE_DIR-NOTFOUND/.."


CMake Error in moonray/moonray/lib/common/mcrt_util/CMakeLists.txt:
  Imported target "Random123::Random123" includes non-existent path

    "Random123_INCLUDE_DIR-NOTFOUND/.."

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in moonray/moonray/lib/rendering/bvh/shading/CMakeLists.txt:
  Target "bvh_shading_ispc" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "Random123_INCLUDE_DIR-NOTFOUND/.."


CMake Error in moonray/moonray/lib/rendering/bvh/shading/ispc/CMakeLists.txt:
  Target "rendering_mcrt_common" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "Random123_INCLUDE_DIR-NOTFOUND/.."


CMake Error in moonray/moonray/lib/rendering/mcrt_common/CMakeLists.txt:
  Target "common_time" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "Random123_INCLUDE_DIR-NOTFOUND/.."
```

After that I get spammed with about 30 screenfulls of that same message.

**Comment by adro79** [comment]
I updated the PKGBUILD following the `namcap` log, hope it helps.

**Comment by alerque** [comment]
We're getting into the meat of the build stage now but still not building:

```
[  2%] Built target routing
[  2%] Built target message_impl
[  2%] Linking CXX shared library librender_logging.so
[  2%] Built target render_logging
[  2%] Linking CXX shared library libarras4_athena.so
[  2%] Linking CXX shared library moonrayShaderParser.so
/usr/bin/ld: cannot find -lar: No such file or directory
/usr/bin/ld: cannot find -lndr: No such file or directory
/usr/bin/ld: cannot find -lsdr: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [moonray/hydra/moonray_sdr_plugins/moonrayShaderParser/CMakeFiles/moonrayShaderParser.dir/build.make:113: moonray/hydra/moonray_sdr_plugins/moonrayShaderParser/moonrayShaderParser.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:10807: moonray/hydra/moonray_sdr_plugins/moonrayShaderParser/CMakeFiles/moonrayShaderParser.dir/all] Error 2
[  2%] Built target arras4_athena
[  2%] Linking CXX shared library hdMoonrayAdapters.so
/usr/bin/ld: cannot find -lusdImaging: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [moonray/hydra/hdMoonray/src/adapters/CMakeFiles/hdMoonrayAdapters.dir/build.make:114: moonray/hydra/hdMoonray/src/adapters/hdMoonrayAdapters.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:10685: moonray/hydra/hdMoonray/src/adapters/CMakeFiles/hdMoonrayAdapters.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
make: Leaving directory '/build/moonray/src/build'
```

**Comment by adro79** [comment]
I forgot about this, but Moonray actually requieres USD to be build without Monolithic support.

**Comment by alerque** [comment]
I've built usd (and put it in [extra-testing] with monolithic support disabled (although we need to confirm that `blender` works with it built this way before we make it official), but that did not get us all the way either. We're a couple percent farther into the build and I get this:

```
/build/moonray/src/openmoonray/moonray/mcrt_denoise/lib/denoiser/OptixDenoiserImpl.cc: In constructor ‘moonray::denoiser::OptixDenoiserImpl::OptixDenoiserImpl(int, int, bool, bool, std::string*)’:
/build/moonray/src/openmoonray/moonray/mcrt_denoise/lib/denoiser/OptixDenoiserImpl.cc:110:36: error: ‘OPTIX_DENOISER_ALPHA_MODE_COPY’ was not declared in this scope
  110 |     mDenoiserParams.denoiseAlpha = OPTIX_DENOISER_ALPHA_MODE_COPY;     // don't denoise alpha
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Is there something special you did with the optix package as well?

**Comment by adro79** [comment]
The patches on the optix.patch are made to support optix 7.6 as this is the lastest version from the [AUR](https://aur.archlinux.org/packages/optix). If you plan to use the recommended optix version (7.3) you can disable the optix patches

**Comment by alerque** [comment]
Interesting, the AUR package has something screwed up because the master branch of the packaging is 7.4 but a dangling commit has 7.6. I just successfully built moonray using 7.6, so this is getting somewhere!

**Comment by alerque** [comment]
Hmm, so that USD change I made made blender unhappy. See [comment here](https://aur.archlinux.org/pkgbase/moonray#comment-953162).

**Pull request merged**
