### PR TITLE
polish brave-bin

### PR DESCRIPTION
**Pull request by roshal**
a couple of visual improvements after #86 were a little late

### CODE REVIEW

**Review by alerque — COMMENTED** [review]
Sorry, I know it is a matter of preference but this is not an improvement in my book. It is a bash script, using bash languages features is not bad, in fact I think the proper bash features are more ergonomic than their POSIX equivalents and and spawning a process to shell out to grep instead of just pattern matching on a string is totally unnecessary overhead.

**Comment by roshal** [comment]
avoiding process spawning makes sense

**Comment by roshal** [comment]
what about avoiding parameter expansion ?

```sh
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
```

there is some confusion between its variations

https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

i constantly forget the difference and how they actually work

```sh
: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
```

some of them are also interchangeable

**Comment by roshal** [comment]
the conditional construct looks more understandable than parameter expansion

```sh
if
	test -z "${XDG_CONFIG_HOME}"
then
	XDG_CONFIG_HOME="${HOME}/.config"
fi
```

also `test` is a shell builtin

**Comment by roshal** [comment]
@alerque reopen pull request please

the branch is updated to take into account the comments

**Comment by alerque** [comment]
I am not really interested in avoiding parameter expansion, sorry. In fact I prefer it to other constructs. You may forget how it works, but other people forget the difference between `test -n`, `test -z`, and `test -v`. As for the other change, the space you added to the pattern matching isn't even valid.

**Comment by roshal** [comment]
i preferred `test -z` because i thought it would be much easier for me and other people to look its flags via `man` than to find a gnu manual especially without knowing in advance about the shell parameter expansion

also the condition construct with `test -f` is already present bellow

```sh
if
	test -f "${CONF_FILE}"
then
	mapfile -t CONF_LIST < "${CONF_FILE}"
fi
```

there are common features between them that may simplify the overall perception

```sh
if
	test -z "${XDG_CONFIG_HOME}"
then
	XDG_CONFIG_HOME="${HOME}/.config"
fi
```

and in my vision sparse is better than dense here

```sh
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
```

we can avoid overwriting the already set `XDG_CONFIG_HOME` variable

**Comment by roshal** [comment]
what added space did you mean ?

```sh
if
	! [[ "${CONF_LINE}" =~ ^[[:space:]]*(#|$) ]]
then
	FLAG_LIST+=("${CONF_LINE}")
fi
```

i do not see anything that is not valid

**Comment by roshal** [comment]
compare [alerque:aur:master...master](https://github.com/roshal/aur--alerque/compare/alerque:aur:master...master)

**Comment by alerque** [comment]
The variable renames are an improvement, but at this point it would just be pointless churn to change them from the current release state. The only overhaul of this launcher I'm interested in is one that follows the coding pattern in the Arch official Electron package launchers which has been revamped from where this started to include some additional protections. Those launchers have proper fallbacks and prevent environment variable injection in a way this one does not. Please stop trying to submit style-only changes to this.

**Pull request closed without merging**
